### ISSUE TITLE
Syntax highlighting doesn't work

### ISSUE THREAD

**Issue by sungam3r** [radiy/vs-graphql-textmate#2]
![изображение](https://user-images.githubusercontent.com/21261007/109305302-922ae900-784e-11eb-9948-b6ba52998357.png)
![изображение](https://user-images.githubusercontent.com/21261007/109305336-a0790500-784e-11eb-89a7-e29423a259e3.png)
![изображение](https://user-images.githubusercontent.com/21261007/109305385-b25aa800-784e-11eb-8109-56b283a8e4cf.png)

**Comment by radiy** [comment]
Better?
![image](https://user-images.githubusercontent.com/341043/109348831-164c9300-7886-11eb-953d-34f86b2391a3.png)

**Comment by radiy** [comment]
Checkout 1.3

**Comment by sungam3r** [comment]
Almost.
![изображение](https://user-images.githubusercontent.com/21261007/109350619-d6d37600-7888-11eb-9872-35be1ce34598.png)
```xml
<?xml version="1.0" encoding="utf-16"?>
<?xml-stylesheet type="text/xsl" href="ActivityLog.xsl"?>
<activity>
  <entry>
    <record>1</record>
    <time>2021/02/26 20:16:39.493</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Microsoft Visual Studio 2019 version: 16.0.31004.167</description>
  </entry>
  <entry>
    <record>2</record>
    <time>2021/02/26 20:16:39.493</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Log ID</description>
    <guid>{E19E4C82-8D73-430C-BC57-43A97B0F6C96}</guid>
  </entry>
  <entry>
    <record>3</record>
    <time>2021/02/26 20:16:39.493</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Running in isolation mode.</description>
  </entry>
  <entry>
    <record>4</record>
    <time>2021/02/26 20:16:39.497</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Looking for master PkgDef file</description>
    <path>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\master.pkgdef</path>
  </entry>
  <entry>
    <record>5</record>
    <time>2021/02/26 20:16:39.498</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Creating PkgDefCacheNonVolatile</description>
  </entry>
  <entry>
    <record>6</record>
    <time>2021/02/26 20:16:39.498</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>PkgDefCache flags</description>
    <hr>00013801</hr>
  </entry>
  <entry>
    <record>7</record>
    <time>2021/02/26 20:16:39.554</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Double-checking master pkgdef file</description>
  </entry>
  <entry>
    <record>8</record>
    <time>2021/02/26 20:16:39.554</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>PkgDefManagement initialized</description>
  </entry>
  <entry>
    <record>9</record>
    <time>2021/02/26 20:16:39.554</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>RootFolder</description>
    <path>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\</path>
  </entry>
  <entry>
    <record>10</record>
    <time>2021/02/26 20:16:39.554</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>ShellFolder</description>
    <path>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\</path>
  </entry>
  <entry>
    <record>1640</record>
    <time>2021/02/26 20:16:43.271</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to set Public Key Token</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1641</record>
    <time>2021/02/26 20:16:43.271</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
    <path>Software\Microsoft\VisualStudio\16.0_718e2e58_Config\RuntimeConfiguration\dependentAssembly\codeBase\{0746BB9F-4F6E-4C38-BCF0-8F601D6AD0C1}</path>
  </entry>
  <entry>
    <record>1642</record>
    <time>2021/02/26 20:16:43.272</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to set Public Key Token</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1643</record>
    <time>2021/02/26 20:16:43.272</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
    <path>Software\Microsoft\VisualStudio\16.0_718e2e58_Config\RuntimeConfiguration\dependentAssembly\codeBase\{167AF614-476E-4BDF-952E-57A6C7CF39A5}</path>
  </entry>
  <entry>
    <record>1644</record>
    <time>2021/02/26 20:16:43.279</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to set Public Key Token</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1645</record>
    <time>2021/02/26 20:16:43.279</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
    <path>Software\Microsoft\VisualStudio\16.0_718e2e58_Config\RuntimeConfiguration\dependentAssembly\codeBase\{7A9AEA02-2F54-493C-8E45-580D66D02799}</path>
  </entry>
  <entry>
    <record>1646</record>
    <time>2021/02/26 20:16:43.279</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to set Public Key Token</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1647</record>
    <time>2021/02/26 20:16:43.279</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
    <path>Software\Microsoft\VisualStudio\16.0_718e2e58_Config\RuntimeConfiguration\dependentAssembly\codeBase\{7E3052B2-FB42-4E38-B22C-1FD281BD4413}</path>
  </entry>
  <entry>
    <record>1648</record>
    <time>2021/02/26 20:16:43.280</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to set Public Key Token</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1649</record>
    <time>2021/02/26 20:16:43.280</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
    <path>Software\Microsoft\VisualStudio\16.0_718e2e58_Config\RuntimeConfiguration\dependentAssembly\codeBase\{938D3E45-5067-45C4-9349-5E939A639CBF}</path>
  </entry>
  <entry>
    <record>1650</record>
    <time>2021/02/26 20:16:43.284</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to set Public Key Token</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1651</record>
    <time>2021/02/26 20:16:43.284</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Binding Redirect / CodeBase entry from configuration hive is malformed, ignoring.</description>
    <hr>80070057 - E_INVALIDARG</hr>
    <errorinfo></errorinfo>
    <path>Software\Microsoft\VisualStudio\16.0_718e2e58_Config\RuntimeConfiguration\dependentAssembly\codeBase\{C8992C7B-8D67-41E9-ADD1-D44D1ACDD139}</path>
  </entry>
  <entry>
    <record>1719</record>
    <time>2021/02/26 20:16:44.720</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{10CA1B00-C23A-4B59-BCE7-512501F4E68A}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'Menus.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>1720</record>
    <time>2021/02/26 20:16:44.720</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package CommandsClientPackage. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>1721</record>
    <time>2021/02/26 20:16:45.001</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{2FFE45C4-5C73-493C-B187-F2E955FF875E}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'Menus.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>1722</record>
    <time>2021/02/26 20:16:45.001</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptPackage, Microsoft.VisualStudio.LanguageServices.TypeScript, Version=16.0.0.0, Culture=neutral. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>1724</record>
    <time>2021/02/26 20:16:45.018</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to find CTMENU resource &apos;#1000&apos; in loaded UI library.</description>
  </entry>
  <entry>
    <record>1725</record>
    <time>2021/02/26 20:16:45.035</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{C78CA057-CC29-421F-AD6D-3B0943DEBDFC}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: '1'.</errorinfo>
  </entry>
  <entry>
    <record>1726</record>
    <time>2021/02/26 20:16:45.035</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package Windows Forms Remote Designer Hosting Package. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>1727</record>
    <time>2021/02/26 20:16:45.063</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{2EF1EC52-C8BF-4FE0-8ECE-BA9C0D5D1603}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'VSMenus.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>1728</record>
    <time>2021/02/26 20:16:45.063</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package XamlLanguagePackage. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>1729</record>
    <time>2021/02/26 20:16:45.159</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{71054795-27FD-4816-9AEA-667FE14EDD2A}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'DialogCommandPackage.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>1730</record>
    <time>2021/02/26 20:16:45.159</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package New Project Dialog. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>2723</record>
    <time>2021/02/26 20:17:12.153</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Tree Navigation Graph Provider&apos; (Microsoft.VisualStudio.TreeNavigation.GraphProvider)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\TREENAVIGATION\GRAPHPROVIDER\</path>
  </entry>
  <entry>
    <record>2724</record>
    <time>2021/02/26 20:17:12.153</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\TREENAVIGATION\GRAPHPROVIDER\</path>
  </entry>
  <entry>
    <record>2725</record>
    <time>2021/02/26 20:17:12.153</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Platform\Visual Studio MPF\16.0\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2726</record>
    <time>2021/02/26 20:17:12.155</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Visual Studio MPF 16.0&apos; (Microsoft.VisualStudio.MPF.16.0)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\VISUAL STUDIO MPF\16.0\</path>
  </entry>
  <entry>
    <record>2727</record>
    <time>2021/02/26 20:17:12.155</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\VISUAL STUDIO MPF\16.0\</path>
  </entry>
  <entry>
    <record>2728</record>
    <time>2021/02/26 20:17:12.155</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\Providers\ManagedProvider\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2729</record>
    <time>2021/02/26 20:17:12.156</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;C# Provider&apos; (Microsoft.VisualStudio.Progression.LanguageService.ManagedProvider)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\MANAGEDPROVIDER\</path>
  </entry>
  <entry>
    <record>2730</record>
    <time>2021/02/26 20:17:12.156</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\MANAGEDPROVIDER\</path>
  </entry>
  <entry>
    <record>2731</record>
    <time>2021/02/26 20:17:12.156</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\Providers\Solution\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2732</record>
    <time>2021/02/26 20:17:12.158</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Solution Provider&apos; (Microsoft.VisualStudio.Progression.VSProvider)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\SOLUTION\</path>
  </entry>
  <entry>
    <record>2733</record>
    <time>2021/02/26 20:17:12.158</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\SOLUTION\</path>
  </entry>
  <entry>
    <record>2734</record>
    <time>2021/02/26 20:17:12.158</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ManagedLanguages\VBCSharp\ExpressionEvaluators\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2735</record>
    <time>2021/02/26 20:17:12.159</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Roslyn Expression Evaluators&apos; (21BAC26D-2935-4D0D-A282-AD647E2592B5)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\EXPRESSIONEVALUATORS\</path>
  </entry>
  <entry>
    <record>2736</record>
    <time>2021/02/26 20:17:12.159</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\EXPRESSIONEVALUATORS\</path>
  </entry>
  <entry>
    <record>2737</record>
    <time>2021/02/26 20:17:12.159</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2738</record>
    <time>2021/02/26 20:17:12.160</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Roslyn Language Services&apos; (0b5e8ddb-f12d-4131-a71d-77acc26a798f)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\LANGUAGESERVICES\</path>
  </entry>
  <entry>
    <record>2739</record>
    <time>2021/02/26 20:17:12.160</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\LANGUAGESERVICES\</path>
  </entry>
  <entry>
    <record>2740</record>
    <time>2021/02/26 20:17:12.160</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ManagedLanguages\VBCSharp\SourceBasedTestDiscovery\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2741</record>
    <time>2021/02/26 20:17:12.160</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Real Time Test Discovery Package&apos; (100cce4d-b061-4215-8fcd-9cb9334929b3)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\SOURCEBASEDTESTDISCOVERY\</path>
  </entry>
  <entry>
    <record>2742</record>
    <time>2021/02/26 20:17:12.160</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\SOURCEBASEDTESTDISCOVERY\</path>
  </entry>
  <entry>
    <record>2743</record>
    <time>2021/02/26 20:17:12.160</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\ChromeDebugAdapter\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2744</record>
    <time>2021/02/26 20:17:12.162</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Error loading extension: There is an error in XML document (12, 5).</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\ChromeDebugAdapter\extension.vsixmanifest</path>
  </entry>
  <entry>
    <record>2745</record>
    <time>2021/02/26 20:17:12.162</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\EdgeDebugAdapter\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2746</record>
    <time>2021/02/26 20:17:12.164</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Error loading extension: There is an error in XML document (12, 5).</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\EdgeDebugAdapter\extension.vsixmanifest</path>
  </entry>
  <entry>
    <record>2747</record>
    <time>2021/02/26 20:17:12.164</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\ToolWindows\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2748</record>
    <time>2021/02/26 20:17:12.166</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;HtmlToolHost&apos; (b66f381b-48de-4c10-b71b-ef9a2a808d85)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\TOOLWINDOWS\</path>
  </entry>
  <entry>
    <record>2749</record>
    <time>2021/02/26 20:17:12.166</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\TOOLWINDOWS\</path>
  </entry>
  <entry>
    <record>2750</record>
    <time>2021/02/26 20:17:12.166</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\WebDiagnosticsAttach\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2751</record>
    <time>2021/02/26 20:17:12.168</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;WebDiagnosticsAttach&apos; (B64A8572-DE00-483C-90ED-E61EB7FEA9BF)...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\WEBDIAGNOSTICSATTACH\</path>
  </entry>
  <entry>
    <record>2752</record>
    <time>2021/02/26 20:17:12.168</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\WEBDIAGNOSTICSATTACH\</path>
  </entry>
  <entry>
    <record>2753</record>
    <time>2021/02/26 20:17:12.168</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Searching folder for extension.vsixmanifest files...</description>
    <path>C:\Users\Crab\AppData\Local\Microsoft\VisualStudio\16.0_718e2e58\Extensions</path>
  </entry>
  <entry>
    <record>2754</record>
    <time>2021/02/26 20:17:12.169</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Capping recursion at 5 directories in each extension root due to &apos;default limit&apos;.</description>
  </entry>
  <entry>
    <record>2755</record>
    <time>2021/02/26 20:17:12.176</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\dfx5jz3m.ms4\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2756</record>
    <time>2021/02/26 20:17:12.176</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Trailing Whitespace Visualizer&apos; (4c1a78e6-e7b8-4aa9-8812-4836e051ff6d)...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\DFX5JZ3M.MS4\</path>
  </entry>
  <entry>
    <record>2757</record>
    <time>2021/02/26 20:17:12.176</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\hhv2tyqe.epf\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2758</record>
    <time>2021/02/26 20:17:12.177</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;GraphQL textmate grammar&apos; (GraphQL.d51e88dc-9e7e-49ad-9a71-bb7dcaa97a12)...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\HHV2TYQE.EPF\</path>
  </entry>
  <entry>
    <record>2759</record>
    <time>2021/02/26 20:17:12.177</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\onulopc2.h40\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2760</record>
    <time>2021/02/26 20:17:12.177</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Visual Studio Spell Checker (VS2017 and Later)&apos; (43EA967E-0DE2-4136-8E52-C6DCFB5C2748)...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\ONULOPC2.H40\</path>
  </entry>
  <entry>
    <record>2761</record>
    <time>2021/02/26 20:17:12.177</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Found &apos;C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\un5cik3g.ct5\extension.vsixmanifest&apos;</description>
  </entry>
  <entry>
    <record>2762</record>
    <time>2021/02/26 20:17:12.178</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension &apos;Markdown Editor&apos; (9ca64947-e9ca-4543-bfb8-6cce9be19fd6)...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\UN5CIK3G.CT5\</path>
  </entry>
  <entry>
    <record>2763</record>
    <time>2021/02/26 20:17:12.179</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\UN5CIK3G.CT5\</path>
  </entry>
  <entry>
    <record>2764</record>
    <time>2021/02/26 20:17:12.179</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\DFX5JZ3M.MS4\</path>
  </entry>
  <entry>
    <record>2765</record>
    <time>2021/02/26 20:17:12.179</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\ONULOPC2.H40\</path>
  </entry>
  <entry>
    <record>2766</record>
    <time>2021/02/26 20:17:12.179</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\HHV2TYQE.EPF\</path>
  </entry>
  <entry>
    <record>2767</record>
    <time>2021/02/26 20:17:12.349</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Skipping &apos;C:\Program Files (x86)\Common Files\Microsoft\ExtensionManager\Extensions&apos; as it doesn&apos;t exist</description>
  </entry>
  <entry>
    <record>2768</record>
    <time>2021/02/26 20:17:12.350</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Searching folder for extension.vsixmanifest files...</description>
    <path>C:\Program Files (x86)\Microsoft SDKs</path>
  </entry>
  <entry>
    <record>2769</record>
    <time>2021/02/26 20:17:12.442</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Skipping &apos;C:\Users\Crab\AppData\Local\Microsoft SDKs&apos; as it doesn&apos;t exist</description>
  </entry>
  <entry>
    <record>2770</record>
    <time>2021/02/26 20:17:12.443</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\UN5CIK3G.CT5\</path>
  </entry>
  <entry>
    <record>2771</record>
    <time>2021/02/26 20:17:12.443</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\DFX5JZ3M.MS4\</path>
  </entry>
  <entry>
    <record>2772</record>
    <time>2021/02/26 20:17:12.443</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\ONULOPC2.H40\</path>
  </entry>
  <entry>
    <record>2773</record>
    <time>2021/02/26 20:17:12.443</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\USERS\CRAB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_718E2E58\EXTENSIONS\HHV2TYQE.EPF\</path>
  </entry>
  <entry>
    <record>2774</record>
    <time>2021/02/26 20:17:12.655</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>VSGallery 0f45e40879954375948586b8db553dc9: Extension &apos;9ca64947-e9ca-4543-bfb8-6cce9be19fd6&apos; has a current version of &apos;1.12.253&apos; that is less than the installed version &apos;1.12.253&apos;</description>
  </entry>
  <entry>
    <record>2775</record>
    <time>2021/02/26 20:17:12.687</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>VSGallery 0f45e40879954375948586b8db553dc9: Extension &apos;43EA967E-0DE2-4136-8E52-C6DCFB5C2748&apos; has a current version of &apos;2021.1.23.0&apos; that is less than the installed version &apos;2021.1.23.0&apos;</description>
  </entry>
  <entry>
    <record>2776</record>
    <time>2021/02/26 20:17:12.707</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>VSGallery 0f45e40879954375948586b8db553dc9: Extension &apos;4c1a78e6-e7b8-4aa9-8812-4836e051ff6d&apos; has a current version of &apos;2.5.95&apos; that is less than the installed version &apos;2.5.95&apos;</description>
  </entry>
  <entry>
    <record>2777</record>
    <time>2021/02/26 20:17:12.721</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>VSGallery 0f45e40879954375948586b8db553dc9: Extension &apos;GraphQL.d51e88dc-9e7e-49ad-9a71-bb7dcaa97a12&apos; has a current version of &apos;1.3&apos; that is less than the installed version &apos;1.3&apos;</description>
  </entry>
  <entry>
    <record>2778</record>
    <time>2021/02/26 20:17:14.987</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Microsoft.VisualStudio.Shell.Connected.AccountManagerService.AccountManagerPackage]</description>
    <guid>{9C987E78-F0BF-45CA-9BA5-96D3E4B2BAC6}</guid>
  </entry>
  <entry>
    <record>2779</record>
    <time>2021/02/26 20:17:14.988</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.Shell.Connected.AccountManagerService.AccountManagerPackage]</description>
    <guid>{9C987E78-F0BF-45CA-9BA5-96D3E4B2BAC6}</guid>
  </entry>
  <entry>
    <record>2780</record>
    <time>2021/02/26 20:17:14.990</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Identity Nexus integration]</description>
    <guid>{F7000CD0-C21D-11EA-B3DE-0242AC130004}</guid>
  </entry>
  <entry>
    <record>2781</record>
    <time>2021/02/26 20:17:14.991</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Identity Nexus integration]</description>
    <guid>{F7000CD0-C21D-11EA-B3DE-0242AC130004}</guid>
  </entry>
  <entry>
    <record>2782</record>
    <time>2021/02/26 20:17:22.803</time>
    <type>Information</type>
    <source>BuiltInSettings</source>
    <description>{&#x000D;&#x000A;  &quot;$schema&quot;: &quot;./WellKnownCloudConfiguration.schema.json&quot;,&#x000D;&#x000A;  &quot;WellKnownClouds&quot;:&#x000D;&#x000A;  [&#x000D;&#x000A;    {&#x000D;&#x000A;      &quot;DisplayName&quot;: &quot;Azure In China&quot;,&#x000D;&#x000A;      &quot;AccountProviderIdentifier&quot;: &quot;552afc90-145a-469c-8c31-943595db4a66&quot;,&#x000D;&#x000A;      &quot;SerializedConfiguration&quot;: &#x000D;&#x000A;      {&#x000D;&#x000A;        &quot;AuthenticationQueryParameters&quot;: null,&#x000D;&#x000A;        &quot;AsmEndPoint&quot;: &quot;https://management.core.chinacloudapi.cn&quot;,&#x000D;&#x000A;        &quot;Authority&quot;: &quot;https://login.chinacloudapi.cn/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementEndpoint&quot;: &quot;https://management.chinacloudapi.cn/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementAudienceEndpoints&quot;: &#x000D;&#x000A;        [&#x000D;&#x000A;          &quot;https://management.core.chinacloudapi.cn/&quot;&#x000D;&#x000A;        ],&#x000D;&#x000A;        &quot;ClientIdentifier&quot;: &quot;872cd9fa-d31f-45e0-9eab-6e460a02d1f1&quot;,&#x000D;&#x000A;        &quot;EnvironmentName&quot;: &quot;Azure In China&quot;,&#x000D;&#x000A;        &quot;GraphEndpoint&quot;: &quot;https://graph.chinacloudapi.cn&quot;,&#x000D;&#x000A;        &quot;MsaHomeTenantId&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,&#x000D;&#x000A;        &quot;NativeClientRedirect&quot;: &quot;urn:ietf:wg:oauth:2.0:oob&quot;,&#x000D;&#x000A;        &quot;PortalEndpoint&quot;: &quot;https://manage.windowsazure.cn&quot;,&#x000D;&#x000A;        &quot;ResourceEndpoint&quot;: &quot;https://management.core.chinacloudapi.cn/&quot;,&#x000D;&#x000A;        &quot;ValidateAuthority&quot;: true,&#x000D;&#x000A;        &quot;VisualStudioOnlineEndpoint&quot;: null,&#x000D;&#x000A;        &quot;VisualStudioOnlineAudience&quot;: null&#x000D;&#x000A;      },&#x000D;&#x000A;      &quot;Authority&quot;: &quot;https://login.chinacloudapi.cn/&quot;,&#x000D;&#x000A;      &quot;AuthorizedVsEdition&quot;: 0,&#x000D;&#x000A;      &quot;Visible&quot;: true&#x000D;&#x000A;    },&#x000D;&#x000A;    {&#x000D;&#x000A;      &quot;DisplayName&quot;: &quot;Azure Germany&quot;,&#x000D;&#x000A;      &quot;AccountProviderIdentifier&quot;: &quot;552afc90-145a-469c-8c31-943595db4a66&quot;,&#x000D;&#x000A;      &quot;SerializedConfiguration&quot;: &#x000D;&#x000A;      {&#x000D;&#x000A;        &quot;AuthenticationQueryParameters&quot;: null,&#x000D;&#x000A;        &quot;AsmEndPoint&quot;: &quot;https://management.microsoftazure.de/&quot;,&#x000D;&#x000A;        &quot;Authority&quot;: &quot;https://login.microsoftonline.de/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementEndpoint&quot;: &quot;https://management.microsoftazure.de/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementAudienceEndpoints&quot;: &#x000D;&#x000A;        [&#x000D;&#x000A;          &quot;https://management.core.cloudapi.de/&quot;&#x000D;&#x000A;        ],&#x000D;&#x000A;        &quot;ClientIdentifier&quot;: &quot;872cd9fa-d31f-45e0-9eab-6e460a02d1f1&quot;,&#x000D;&#x000A;        &quot;EnvironmentName&quot;: &quot;Azure Germany&quot;,&#x000D;&#x000A;        &quot;GraphEndpoint&quot;: &quot;https://graph.cloudapi.de&quot;,&#x000D;&#x000A;        &quot;MsaHomeTenantId&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,&#x000D;&#x000A;        &quot;NativeClientRedirect&quot;: &quot;urn:ietf:wg:oauth:2.0:oob&quot;,&#x000D;&#x000A;        &quot;PortalEndpoint&quot;: &quot;https://portal.core.cloudapi.de/&quot;,&#x000D;&#x000A;        &quot;ResourceEndpoint&quot;: &quot;https://management.core.cloudapi.de/&quot;,&#x000D;&#x000A;        &quot;ValidateAuthority&quot;: true,&#x000D;&#x000A;        &quot;VisualStudioOnlineEndpoint&quot;: null,&#x000D;&#x000A;        &quot;VisualStudioOnlineAudience&quot;: null&#x000D;&#x000A;      },&#x000D;&#x000A;      &quot;Authority&quot;: &quot;https://login.microsoftonline.de/&quot;,&#x000D;&#x000A;      &quot;AuthorizedVsEdition&quot;: 0,&#x000D;&#x000A;      &quot;Visible&quot;: true&#x000D;&#x000A;    },&#x000D;&#x000A;    {&#x000D;&#x000A;      &quot;DisplayName&quot;: &quot;Azure U.S. Government&quot;,&#x000D;&#x000A;      &quot;AccountProviderIdentifier&quot;: &quot;552afc90-145a-469c-8c31-943595db4a66&quot;,&#x000D;&#x000A;      &quot;SerializedConfiguration&quot;:&#x000D;&#x000A;      {&#x000D;&#x000A;        &quot;AuthenticationQueryParameters&quot;: null,&#x000D;&#x000A;        &quot;AsmEndPoint&quot;: &quot;https://management.core.usgovcloudapi.net/&quot;,&#x000D;&#x000A;        &quot;Authority&quot;: &quot;https://login.microsoftonline.us/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementEndpoint&quot;: &quot;https://management.usgovcloudapi.net&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementAudienceEndpoints&quot;:&#x000D;&#x000A;        [&#x000D;&#x000A;          &quot;https://management.core.usgovcloudapi.net&quot;&#x000D;&#x000A;        ],&#x000D;&#x000A;        &quot;ClientIdentifier&quot;: &quot;872cd9fa-d31f-45e0-9eab-6e460a02d1f1&quot;,&#x000D;&#x000A;        &quot;EnvironmentName&quot;: &quot;Azure U.S. Government&quot;,&#x000D;&#x000A;        &quot;GraphEndpoint&quot;: &quot;https://graph.microsoftazure.us&quot;,&#x000D;&#x000A;        &quot;MsaHomeTenantId&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,&#x000D;&#x000A;        &quot;NativeClientRedirect&quot;: &quot;https://login.microsoftonline.com/common/oauth2/nativeclient&quot;,&#x000D;&#x000A;        &quot;PortalEndpoint&quot;: &quot;https://portal.azure.us/&quot;,&#x000D;&#x000A;        &quot;ResourceEndpoint&quot;: &quot;https://management.core.usgovcloudapi.net&quot;,&#x000D;&#x000A;        &quot;ValidateAuthority&quot;: true,&#x000D;&#x000A;        &quot;VisualStudioOnlineEndpoint&quot;: null,&#x000D;&#x000A;        &quot;VisualStudioOnlineAudience&quot;: null&#x000D;&#x000A;      },&#x000D;&#x000A;      &quot;Authority&quot;: &quot;https://login.microsoftonline.us/&quot;,&#x000D;&#x000A;      &quot;AuthorizedVsEdition&quot;: 0,&#x000D;&#x000A;      &quot;Visible&quot;: true&#x000D;&#x000A;    },&#x000D;&#x000A;{&#x000D;&#x000A;      &quot;DisplayName&quot;: &quot;Azure U.S. Government Legacy&quot;,&#x000D;&#x000A;      &quot;AccountProviderIdentifier&quot;: &quot;552afc90-145a-469c-8c31-943595db4a66&quot;,&#x000D;&#x000A;      &quot;SerializedConfiguration&quot;:&#x000D;&#x000A;      {&#x000D;&#x000A;        &quot;AuthenticationQueryParameters&quot;: null,&#x000D;&#x000A;        &quot;AsmEndPoint&quot;: &quot;https://management.core.usgovcloudapi.net/&quot;,&#x000D;&#x000A;        &quot;Authority&quot;: &quot;https://login.microsoftonline.us/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementEndpoint&quot;: &quot;https://management.usgovcloudapi.net&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementAudienceEndpoints&quot;:&#x000D;&#x000A;        [&#x000D;&#x000A;          &quot;https://management.core.usgovcloudapi.net&quot;&#x000D;&#x000A;        ],&#x000D;&#x000A;        &quot;ClientIdentifier&quot;: &quot;872cd9fa-d31f-45e0-9eab-6e460a02d1f1&quot;,&#x000D;&#x000A;        &quot;EnvironmentName&quot;: &quot;Azure U.S. Government&quot;,&#x000D;&#x000A;        &quot;GraphEndpoint&quot;: &quot;https://graph.windows.net&quot;,&#x000D;&#x000A;        &quot;MsaHomeTenantId&quot;: &quot;f8cdef31-a31e-4b4a-93e4-5f571e91255a&quot;,&#x000D;&#x000A;        &quot;NativeClientRedirect&quot;: &quot;urn:ietf:wg:oauth:2.0:oob&quot;,&#x000D;&#x000A;        &quot;PortalEndpoint&quot;: &quot;https://portal.azure.us/&quot;,&#x000D;&#x000A;        &quot;ResourceEndpoint&quot;: &quot;https://management.core.usgovcloudapi.net&quot;,&#x000D;&#x000A;        &quot;ValidateAuthority&quot;: true,&#x000D;&#x000A;        &quot;VisualStudioOnlineEndpoint&quot;: &quot;https://app.vssps.visualstudio.com/&quot;,&#x000D;&#x000A;        &quot;VisualStudioOnlineAudience&quot;: &quot;499b84ac-1321-427f-aa17-267ca6975798&quot;&#x000D;&#x000A;      },&#x000D;&#x000A;      &quot;Authority&quot;: &quot;https://login.microsoftonline.us/&quot;,&#x000D;&#x000A;      &quot;AuthorizedVsEdition&quot;: 0,&#x000D;&#x000A;      &quot;Visible&quot;: true&#x000D;&#x000A;    },&#x000D;&#x000A;    {&#x000D;&#x000A;      &quot;DisplayName&quot;: &quot;Azure Government Legacy Authority&quot;,&#x000D;&#x000A;      &quot;AccountProviderIdentifier&quot;: &quot;552afc90-145a-469c-8c31-943595db4a66&quot;,&#x000D;&#x000A;      &quot;SerializedConfiguration&quot;:&#x000D;&#x000A;      {&#x000D;&#x000A;        &quot;AuthenticationQueryParameters&quot;: null,&#x000D;&#x000A;        &quot;AsmEndPoint&quot;: &quot;https://management.core.usgovcloudapi.net/&quot;,&#x000D;&#x000A;        &quot;Authority&quot;: &quot;https://login-us.microsoftonline.com/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementEndpoint&quot;: &quot;https://management.usgovcloudapi.net&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementAudienceEndpoints&quot;:&#x000D;&#x000A;        [&#x000D;&#x000A;          &quot;https://management.core.usgovcloudapi.net&quot;&#x000D;&#x000A;        ],&#x000D;&#x000A;        &quot;ClientIdentifier&quot;: &quot;872cd9fa-d31f-45e0-9eab-6e460a02d1f1&quot;,&#x000D;&#x000A;        &quot;EnvironmentName&quot;: &quot;Azure U.S. Government&quot;,&#x000D;&#x000A;        &quot;GraphEndpoint&quot;: &quot;https://graph.windows.net&quot;,&#x000D;&#x000A;        &quot;MsaHomeTenantId&quot;: &quot;f8cdef31-a31e-4b4a-93e4-5f571e91255a&quot;,&#x000D;&#x000A;        &quot;NativeClientRedirect&quot;: &quot;urn:ietf:wg:oauth:2.0:oob&quot;,&#x000D;&#x000A;        &quot;PortalEndpoint&quot;: &quot;https://portal.azure.us/&quot;,&#x000D;&#x000A;        &quot;ResourceEndpoint&quot;: &quot;https://management.core.usgovcloudapi.net&quot;,&#x000D;&#x000A;        &quot;ValidateAuthority&quot;: true,&#x000D;&#x000A;        &quot;VisualStudioOnlineEndpoint&quot;: &quot;https://app.vssps.visualstudio.com/&quot;,&#x000D;&#x000A;        &quot;VisualStudioOnlineAudience&quot;: &quot;499b84ac-1321-427f-aa17-267ca6975798&quot;&#x000D;&#x000A;      },&#x000D;&#x000A;      &quot;Authority&quot;: &quot;https://login-us.microsoftonline.com/&quot;,&#x000D;&#x000A;      &quot;AuthorizedVsEdition&quot;: 0,&#x000D;&#x000A;      &quot;Visible&quot;: false&#x000D;&#x000A;    },&#x000D;&#x000A;    {&#x000D;&#x000A;      &quot;DisplayName&quot;: &quot;Azure&quot;,&#x000D;&#x000A;      &quot;AccountProviderIdentifier&quot;: &quot;552afc90-145a-469c-8c31-943595db4a66&quot;,&#x000D;&#x000A;      &quot;SerializedConfiguration&quot;:&#x000D;&#x000A;      {&#x000D;&#x000A;        &quot;AuthenticationQueryParameters&quot;: null,&#x000D;&#x000A;        &quot;AsmEndPoint&quot;: &quot;https://management.core.windows.net/&quot;,&#x000D;&#x000A;        &quot;Authority&quot;: &quot;https://login.microsoftonline.com/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementEndpoint&quot;: &quot;https://management.azure.com/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementAudienceEndpoints&quot;:&#x000D;&#x000A;        [&#x000D;&#x000A;          &quot;https://management.core.windows.net/&quot;&#x000D;&#x000A;        ],&#x000D;&#x000A;        &quot;ClientIdentifier&quot;: &quot;872cd9fa-d31f-45e0-9eab-6e460a02d1f1&quot;,&#x000D;&#x000A;        &quot;EnvironmentName&quot;: &quot;AzureCloud&quot;,&#x000D;&#x000A;        &quot;GraphEndpoint&quot;: &quot;https://graph.windows.net/&quot;,&#x000D;&#x000A;        &quot;MsaHomeTenantId&quot;: &quot;f8cdef31-a31e-4b4a-93e4-5f571e91255a&quot;,&#x000D;&#x000A;        &quot;NativeClientRedirect&quot;: &quot;urn:ietf:wg:oauth:2.0:oob&quot;,&#x000D;&#x000A;        &quot;PortalEndpoint&quot;: &quot;https://portal.azure.com/&quot;,&#x000D;&#x000A;        &quot;ResourceEndpoint&quot;: &quot;https://management.core.windows.net/&quot;,&#x000D;&#x000A;        &quot;ValidateAuthority&quot;: true,&#x000D;&#x000A;        &quot;VisualStudioOnlineEndpoint&quot;: &quot;https://app.vssps.visualstudio.com/&quot;,&#x000D;&#x000A;        &quot;VisualStudioOnlineAudience&quot;: &quot;499b84ac-1321-427f-aa17-267ca6975798&quot;&#x000D;&#x000A;      },&#x000D;&#x000A;      &quot;Authority&quot;: &quot;https://login.microsoftonline.com/&quot;,&#x000D;&#x000A;      &quot;AuthorizedVsEdition&quot;: 0,&#x000D;&#x000A;      &quot;Visible&quot;: false&#x000D;&#x000A;    },&#x000D;&#x000A;    {&#x000D;&#x000A;      &quot;DisplayName&quot;: &quot;Azure PPE&quot;,&#x000D;&#x000A;      &quot;AccountProviderIdentifier&quot;: &quot;552afc90-145a-469c-8c31-943595db4a66&quot;,&#x000D;&#x000A;      &quot;SerializedConfiguration&quot;:&#x000D;&#x000A;      {&#x000D;&#x000A;        &quot;AuthenticationQueryParameters&quot;: null,&#x000D;&#x000A;        &quot;AsmEndPoint&quot;: &quot;https://management.core.windows.net/&quot;,&#x000D;&#x000A;        &quot;Authority&quot;: &quot;https://login.windows-ppe.net/&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementEndpoint&quot;: &quot;https://api-dogfood.resources.windows-int.net&quot;,&#x000D;&#x000A;        &quot;AzureResourceManagementAudienceEndpoints&quot;:&#x000D;&#x000A;        [&#x000D;&#x000A;          &quot;https://api-dogfood.resources.windows-int.net&quot;&#x000D;&#x000A;        ],&#x000D;&#x000A;        &quot;ClientIdentifier&quot;: &quot;872cd9fa-d31f-45e0-9eab-6e460a02d1f1&quot;,&#x000D;&#x000A;        &quot;EnvironmentName&quot;: &quot;Azure PPE&quot;,&#x000D;&#x000A;        &quot;GraphEndpoint&quot;: &quot;https://graph.ppe.windows.net/&quot;,&#x000D;&#x000A;        &quot;MsaHomeTenantId&quot;: &quot;ea8a4392-515e-481f-879e-6571ff2a8a36&quot;,&#x000D;&#x000A;        &quot;NativeClientRedirect&quot;: &quot;urn:ietf:wg:oauth:2.0:oob&quot;,&#x000D;&#x000A;        &quot;PortalEndpoint&quot;: &quot;https://portal.azure.com/&quot;,&#x000D;&#x000A;        &quot;ResourceEndpoint&quot;: &quot;https://management.core.windows.net/&quot;,&#x000D;&#x000A;        &quot;ValidateAuthority&quot;: true,&#x000D;&#x000A;        &quot;VisualStudioOnlineEndpoint&quot;: &quot;https://app.spsfsint3.tfsallin.net/&quot;,&#x000D;&#x000A;        &quot;VisualStudioOnlineAudience&quot;: &quot;499b84ac-1321-427f-aa17-267ca6975798&quot;&#x000D;&#x000A;      },&#x000D;&#x000A;      &quot;Authority&quot;: &quot;https://login.windows-ppe.net/&quot;,&#x000D;&#x000A;      &quot;AuthorizedVsEdition&quot;: 0,&#x000D;&#x000A;      &quot;Visible&quot;: false&#x000D;&#x000A;    }&#x000D;&#x000A;  ]&#x000D;&#x000A;}</description>
  </entry>
  <entry>
    <record>2783</record>
    <time>2021/02/26 20:17:24.374</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Running in User Groups: Users</description>
  </entry>
  <entry>
    <record>2784</record>
    <time>2021/02/26 20:17:24.375</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Available Drive Space: C:\ drive has 2020249600 bytes; F:\ drive has 85389529088 bytes</description>
  </entry>
  <entry>
    <record>2785</record>
    <time>2021/02/26 20:17:24.379</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Internet Explorer Version: 11.0.16299.726</description>
  </entry>
  <entry>
    <record>2786</record>
    <time>2021/02/26 20:17:24.379</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>.NET Framework Version: 10.0.16299.15</description>
  </entry>
  <entry>
    <record>2787</record>
    <time>2021/02/26 20:17:24.379</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>MSXML Version: 6.30.16299.726</description>
  </entry>
  <entry>
    <record>2788</record>
    <time>2021/02/26 20:17:27.078</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [VSSpellCheckEverywherePackage]</description>
    <guid>{A447DC7A-A901-442C-B183-87DCBF015C1E}</guid>
  </entry>
  <entry>
    <record>2789</record>
    <time>2021/02/26 20:17:27.129</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Microsoft.VisualStudio.Shell.Connected.ConnectedUser.ConnectedUserPackage]</description>
    <guid>{7F679D93-2EB6-47C9-85EB-F6AD16902662}</guid>
  </entry>
  <entry>
    <record>2790</record>
    <time>2021/02/26 20:17:27.469</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Starting update</description>
  </entry>
  <entry>
    <record>2791</record>
    <time>2021/02/26 20:17:27.491</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Cleaning cache directory</description>
  </entry>
  <entry>
    <record>2792</record>
    <time>2021/02/26 20:17:27.501</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Local database file exists. Patching local database</description>
  </entry>
  <entry>
    <record>2793</record>
    <time>2021/02/26 20:17:27.515</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Patching local database</description>
  </entry>
  <entry>
    <record>2794</record>
    <time>2021/02/26 20:17:27.531</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Reading in local database</description>
  </entry>
  <entry>
    <record>2795</record>
    <time>2021/02/26 20:17:27.547</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Reading in local database completed. databaseBytes.Length=9337312</description>
  </entry>
  <entry>
    <record>2796</record>
    <time>2021/02/26 20:17:27.563</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Creating database from bytes</description>
  </entry>
  <entry>
    <record>2797</record>
    <time>2021/02/26 20:17:27.581</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
  </entry>
  <entry>
    <record>2798</record>
    <time>2021/02/26 20:17:27.595</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Creating database from bytes completed</description>
  </entry>
  <entry>
    <record>2799</record>
    <time>2021/02/26 20:17:27.606</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Downloading and processing patch file: Elfie_V1/20201029_Patch.xml</description>
  </entry>
  <entry>
    <record>2800</record>
    <time>2021/02/26 20:17:27.611</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Creating download client: Elfie_V1/20201029_Patch.xml</description>
  </entry>
  <entry>
    <record>2801</record>
    <time>2021/02/26 20:17:27.627</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Creating download client completed</description>
  </entry>
  <entry>
    <record>2802</record>
    <time>2021/02/26 20:17:27.643</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Read file from client</description>
  </entry>
  <entry>
    <record>2803</record>
    <time>2021/02/26 20:17:27.659</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Read file completed. Client returned data</description>
  </entry>
  <entry>
    <record>2804</record>
    <time>2021/02/26 20:17:27.675</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Converting data to XElement</description>
  </entry>
  <entry>
    <record>2805</record>
    <time>2021/02/26 20:17:27.691</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Converting data to XElement completed</description>
  </entry>
  <entry>
    <record>2806</record>
    <time>2021/02/26 20:17:27.703</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Processing patch element</description>
  </entry>
  <entry>
    <record>2807</record>
    <time>2021/02/26 20:17:27.723</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Local version is up to date</description>
  </entry>
  <entry>
    <record>2808</record>
    <time>2021/02/26 20:17:27.754</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Processing patch element completed. Update again in 1.00:00:00</description>
  </entry>
  <entry>
    <record>2809</record>
    <time>2021/02/26 20:17:27.771</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Downloading and processing patch file completed</description>
  </entry>
  <entry>
    <record>2810</record>
    <time>2021/02/26 20:17:27.781</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Patching local database completed</description>
  </entry>
  <entry>
    <record>2811</record>
    <time>2021/02/26 20:17:27.801</time>
    <type>Information</type>
    <source>RoslynNuGetSearch</source>
    <description>Waiting 1.00:00:00 until next update</description>
  </entry>
  <entry>
    <record>2812</record>
    <time>2021/02/26 20:17:27.831</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [VSSpellCheckEverywherePackage]</description>
    <guid>{A447DC7A-A901-442C-B183-87DCBF015C1E}</guid>
  </entry>
  <entry>
    <record>2813</record>
    <time>2021/02/26 20:17:27.844</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.Shell.Connected.ConnectedUser.ConnectedUserPackage]</description>
    <guid>{7F679D93-2EB6-47C9-85EB-F6AD16902662}</guid>
  </entry>
  <entry>
    <record>2814</record>
    <time>2021/02/26 20:17:27.859</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Microsoft.VisualStudio.Shell.Connected.Packages.OnlineLicensing.OnlineLicensingManagerPackage]</description>
    <guid>{A5C25D8F-4D74-4924-BD8C-F3C2B860F4EC}</guid>
  </entry>
  <entry>
    <record>2815</record>
    <time>2021/02/26 20:17:27.860</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.Shell.Connected.Packages.OnlineLicensing.OnlineLicensingManagerPackage]</description>
    <guid>{A5C25D8F-4D74-4924-BD8C-F3C2B860F4EC}</guid>
  </entry>
  <entry>
    <record>2816</record>
    <time>2021/02/26 20:17:27.863</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [ManagedProjectSystemPackage]</description>
    <guid>{860A27C0-B665-47F3-BC12-637E16A1050A}</guid>
  </entry>
  <entry>
    <record>2817</record>
    <time>2021/02/26 20:17:27.882</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
  </entry>
  <entry>
    <record>2818</record>
    <time>2021/02/26 20:17:27.896</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [VS Setup Composition]</description>
    <guid>{F92174FD-F10D-418B-819A-7433DEA53833}</guid>
  </entry>
  <entry>
    <record>2819</record>
    <time>2021/02/26 20:17:27.904</time>
    <type>Information</type>
    <source>UserConnection</source>
    <description>Manager ServerUri &apos;https://go.microsoft.com/fwlink/?LinkID=660932&apos;</description>
  </entry>
  <entry>
    <record>2820</record>
    <time>2021/02/26 20:17:27.935</time>
    <type>Information</type>
    <source>UserConnection</source>
    <description>Unresolved FW Link &apos;https://go.microsoft.com/fwlink/?LinkID=660932&apos; was resolved to &apos;https://app.vssps.visualstudio.com/&apos;</description>
  </entry>
  <entry>
    <record>2821</record>
    <time>2021/02/26 20:17:28.118</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CommonEditorPackage]</description>
    <guid>{37F69003-4AC4-4B33-AA3A-4D620BE07696}</guid>
  </entry>
  <entry>
    <record>2822</record>
    <time>2021/02/26 20:17:28.134</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [CommonEditorPackage]</description>
    <guid>{37F69003-4AC4-4B33-AA3A-4D620BE07696}</guid>
  </entry>
</activity>
```

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/109350813-3762b300-7889-11eb-900a-933ed23723a5.png)
![изображение](https://user-images.githubusercontent.com/21261007/109350874-53feeb00-7889-11eb-8da9-165f5fef1c40.png)
However, I admit that the highlighting is better now.

**Comment by radiy** [comment]
Fixed in 1.4
![image](https://user-images.githubusercontent.com/341043/109422629-685bf880-79ed-11eb-9ecc-0955f9b757b4.png)

**Comment by sungam3r** [comment]
👍

**Comment by sungam3r** [comment]
Installation failed
![изображение](https://user-images.githubusercontent.com/21261007/109422790-1ff10a80-79ee-11eb-86f8-d4687fe20920.png)

**Comment by radiy** [comment]
Not sure what went wrong, I tested updated version on different machine and update went just fine.
Try to uninstall/install.

**Comment by sungam3r** [comment]
I did that, but the extension still shows up as installed, and it doesn't work. On the third try it worked.
![изображение](https://user-images.githubusercontent.com/21261007/109429652-e0d2b180-7a0d-11eb-8ee1-3a79180d7c00.png)

**Comment by sungam3r** [comment]
Thanks!
